### ISSUE TITLE
Starting merger without `common-forked-blocks-store-url` generates error

### ISSUE THREAD

**Issue by matthewdarwin** [EOS-Nation/firehose-antelope#26]
Don't specify any storage locations.  It should default to the datadir specified with `-d` (which is /var/lib/dfuse in our case.  Get weird error:

```
Error: unable to launch: failed to init destination archive store: parse "file://{sf-data-dir}/storage/forked-blocks": invalid character "{" in host name
2022-11-26T17:03:44.884Z ERRO (derr) acme-blockchain {"error": "unable to launch: failed to init destination archive store: parse \"file://{sf-data-dir}/storage/forked-blocks\": invalid character \"{\" in host name"}
```

Example:

```
$ /usr/bin/fireantelope -d /var/lib/dfuse -c /etc/dfuse/config.yml start
```

config.yml:

```
start:
  args:
  - reader-node-stdin
  - merger
  flags:
    verbose: 0
    reader-node-grpc-listen-addr: :9000
    common-first-streamable-block: 1
```
