### ISSUE TITLE
update `sf.antelope.type.v1` => `v2`

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/firehose-antelope#48]
Using `sf.antelope.type.v1.Block` native source does not work with Substreams

However, the protobuf file is using `sf.antelope.type.v1`

- [ ] change any protobuf to `v2`
- [ ] update folder to `v2`
- [ ] replace `streamingfast` references to `pinax-network`

https://github.com/pinax-network/firehose-antelope/blob/feature/decode_db_ops/proto/sf/antelope/type/v1/type.proto#L3-L5

## Substreams

```yaml
modules:
  - name: map_active_schedule
    kind: map
    inputs:
      - source: sf.antelope.type.v1.Block
    output:
      type: proto:sf.antelope.type.v2.ProducerAuthoritySchedule
```

## Error ❌ 
> Error: rpc error: code = Internal desc = step new irr: handler step new: execute modules: running executor "map_active_schedule": execute module: execute: execute: maps wasm call: input data for "sf.antelope.type.v1.Block": inputs module value not found
